
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author prayag
 */
public class FastCash extends javax.swing.JFrame {

    /**
     * Creates new form FastCash
     */
    String firstName;
    String firstEmail;
    String firstCardno;
    String firstPin;
    int balance;

    public FastCash() {
        initComponents();
    }

    public FastCash(String firstName, String firstEmail, String firstCardno, String firstPin, int balance) {
        this.firstName = firstName;
        this.firstEmail = firstEmail;
        this.firstCardno = firstCardno;
        this.firstPin = firstPin;
        this.balance = balance;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1000 = new javax.swing.JButton();
        btn2000 = new javax.swing.JButton();
        btn4000 = new javax.swing.JButton();
        btn6000 = new javax.swing.JButton();
        btn8000 = new javax.swing.JButton();
        btn10000 = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_bankname1 = new javax.swing.JLabel();
        lbl_banktext1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn1000.setBackground(new java.awt.Color(204, 0, 0));
        btn1000.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn1000.setForeground(new java.awt.Color(255, 255, 255));
        btn1000.setText("1000");
        btn1000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000ActionPerformed(evt);
            }
        });

        btn2000.setBackground(new java.awt.Color(204, 0, 0));
        btn2000.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn2000.setForeground(new java.awt.Color(255, 255, 255));
        btn2000.setText("2000");
        btn2000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2000ActionPerformed(evt);
            }
        });

        btn4000.setBackground(new java.awt.Color(204, 0, 0));
        btn4000.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn4000.setForeground(new java.awt.Color(255, 255, 255));
        btn4000.setText("4000");
        btn4000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn4000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4000ActionPerformed(evt);
            }
        });

        btn6000.setBackground(new java.awt.Color(204, 0, 0));
        btn6000.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn6000.setForeground(new java.awt.Color(255, 255, 255));
        btn6000.setText("6000");
        btn6000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn6000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6000ActionPerformed(evt);
            }
        });

        btn8000.setBackground(new java.awt.Color(204, 0, 0));
        btn8000.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn8000.setForeground(new java.awt.Color(255, 255, 255));
        btn8000.setText("8000");
        btn8000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn8000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8000ActionPerformed(evt);
            }
        });

        btn10000.setBackground(new java.awt.Color(204, 0, 0));
        btn10000.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn10000.setForeground(new java.awt.Color(255, 255, 255));
        btn10000.setText("10000");
        btn10000.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10000ActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(204, 0, 0));
        btncancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("Cancel");
        btncancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 0, 204));

        lbl_bankname1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lbl_bankname1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bankname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bankname1.setText("HDFC BANK");

        lbl_banktext1.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lbl_banktext1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_banktext1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_banktext1.setText("Select fast cash");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_banktext1)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_bankname1)
                        .addGap(137, 137, 137))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lbl_bankname1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_banktext1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn4000, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(btn2000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn8000, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6000, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10000, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1000)
                    .addComponent(btn6000))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2000)
                    .addComponent(btn8000))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4000)
                    .addComponent(btn10000))
                .addGap(32, 32, 32)
                .addComponent(btncancel)
                .addGap(18, 18, 18))
        );

        setBounds(0, 0, 440, 389);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000ActionPerformed
        int balance = this.balance;
        if (balance > 1000) {
            balance = balance - 1000;
            String message = "You have successfully withdrawed " + 1000 + " rupees.";
            JOptionPane.showMessageDialog(this, message);
            Complete complete = new Complete(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, balance);
            complete.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Insufficent balance.");
        }

    }//GEN-LAST:event_btn1000ActionPerformed

    private void btn2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2000ActionPerformed
        int balance = this.balance;
        if (balance > 2000) {
            balance = balance - 2000;
            String message = "You have successfully withdrawed " + 2000 + " rupees.";
            JOptionPane.showMessageDialog(this, message);
            Complete complete = new Complete(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, balance);
            complete.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Insufficent balance.");
        }
    }//GEN-LAST:event_btn2000ActionPerformed

    private void btn4000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4000ActionPerformed
        int balance = this.balance;
        if (balance > 4000) {
            balance = balance - 4000;
            String message = "You have successfully withdrawed " + 4000 + " rupees.";
            JOptionPane.showMessageDialog(this, message);
            Complete complete = new Complete(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, balance);
            complete.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Insufficent balance.");
        }
    }//GEN-LAST:event_btn4000ActionPerformed

    private void btn6000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6000ActionPerformed
        int balance = this.balance;
        if (balance > 6000) {
            balance = balance - 6000;
            String message = "You have successfully withdrawed " + 6000 + " rupees.";
            JOptionPane.showMessageDialog(this, message);
            Complete complete = new Complete(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, balance);
            complete.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Insufficent balance.");
        }
    }//GEN-LAST:event_btn6000ActionPerformed

    private void btn8000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8000ActionPerformed
        int balance = this.balance;
        if (balance > 8000) {
            balance = balance - 8000;
            String message = "You have successfully withdrawed " + 8000 + " rupees.";
            JOptionPane.showMessageDialog(this, message);
            Complete complete = new Complete(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, balance);
            complete.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Insufficent balance.");
        }
    }//GEN-LAST:event_btn8000ActionPerformed

    private void btn10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10000ActionPerformed
        int balance = this.balance;
        if (balance > 10000) {
            balance = balance - 10000;
            String message = "You have successfully withdrawed " + 10000 + " rupees.";
            JOptionPane.showMessageDialog(this, message);
            Complete complete = new Complete(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, balance);
            complete.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Insufficent balance.");
        }
    }//GEN-LAST:event_btn10000ActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        First first = new First(this.firstName,this.firstEmail,this.firstCardno, this.firstPin, this.balance);
        first.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1000;
    private javax.swing.JButton btn10000;
    private javax.swing.JButton btn2000;
    private javax.swing.JButton btn4000;
    private javax.swing.JButton btn6000;
    private javax.swing.JButton btn8000;
    private javax.swing.JButton btncancel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_bankname1;
    private javax.swing.JLabel lbl_banktext1;
    // End of variables declaration//GEN-END:variables
}
