/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author prayag
 */
public class First extends javax.swing.JFrame {

    /**
     * Creates new form First
     */
    String signinCardno;
    String signinPin;
    int balance;
    String signinName;
    String signinEmail;

    public First() {
        initComponents();
    }

    public First(String signinName, String signinEmail, String signinCardno, String signinPin, int balance) {

        this.signinCardno = signinCardno;
        this.signinPin = signinPin;
        this.balance = balance;
        this.signinName = signinName;
        this.signinEmail = signinEmail;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btndeposit = new javax.swing.JButton();
        btnwithdrawal = new javax.swing.JButton();
        btnfastcash = new javax.swing.JButton();
        btnpinchange = new javax.swing.JButton();
        btnbalanceenquiry = new javax.swing.JButton();
        btnministatement = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_bankname1 = new javax.swing.JLabel();
        lbl_banktext1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("CHOOSE A TRANSACTION");

        btndeposit.setBackground(new java.awt.Color(204, 0, 0));
        btndeposit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndeposit.setForeground(new java.awt.Color(255, 255, 255));
        btndeposit.setText("DEPOSIT");
        btndeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositActionPerformed(evt);
            }
        });

        btnwithdrawal.setBackground(new java.awt.Color(204, 0, 0));
        btnwithdrawal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnwithdrawal.setForeground(new java.awt.Color(255, 255, 255));
        btnwithdrawal.setText("WITHDRAWAL");
        btnwithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnwithdrawalActionPerformed(evt);
            }
        });

        btnfastcash.setBackground(new java.awt.Color(204, 0, 0));
        btnfastcash.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnfastcash.setForeground(new java.awt.Color(255, 255, 255));
        btnfastcash.setText("FAST CASH");
        btnfastcash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfastcashActionPerformed(evt);
            }
        });

        btnpinchange.setBackground(new java.awt.Color(204, 0, 0));
        btnpinchange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnpinchange.setForeground(new java.awt.Color(255, 255, 255));
        btnpinchange.setText("PIN CHANGE");
        btnpinchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpinchangeActionPerformed(evt);
            }
        });

        btnbalanceenquiry.setBackground(new java.awt.Color(204, 0, 0));
        btnbalanceenquiry.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbalanceenquiry.setForeground(new java.awt.Color(255, 255, 255));
        btnbalanceenquiry.setText("BALANCE ENQUIRY");
        btnbalanceenquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbalanceenquiryActionPerformed(evt);
            }
        });

        btnministatement.setBackground(new java.awt.Color(204, 0, 0));
        btnministatement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnministatement.setForeground(new java.awt.Color(255, 255, 255));
        btnministatement.setText("MINI STATEMENT");
        btnministatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnministatementActionPerformed(evt);
            }
        });

        btncancel.setBackground(new java.awt.Color(204, 0, 0));
        btncancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncancel.setForeground(new java.awt.Color(255, 255, 255));
        btncancel.setText("CANCEL");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 0, 204));

        lbl_bankname1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        lbl_bankname1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bankname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bankname1.setText("HDFC BANK");

        lbl_banktext1.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lbl_banktext1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_banktext1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_banktext1.setText("Menu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_bankname1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbl_banktext1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lbl_bankname1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_banktext1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(233, 233, 233))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btndeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnfastcash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnwithdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnministatement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnbalanceenquiry, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(49, 49, 49)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(btnpinchange, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpinchange, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbalanceenquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnwithdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnministatement, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfastcash, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositActionPerformed
        Deposit deposit = new Deposit(this.signinName, this.signinEmail, this.signinCardno, this.signinPin, this.balance);
        deposit.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btndepositActionPerformed

    private void btnfastcashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfastcashActionPerformed
        FastCash fastCash = new FastCash(this.signinName, this.signinEmail, this.signinCardno, this.signinPin, this.balance);
        fastCash.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnfastcashActionPerformed

    private void btnpinchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpinchangeActionPerformed
        PinChange pinChange = new PinChange(this.signinName, this.signinEmail, this.signinCardno, this.signinPin, this.balance);
        pinChange.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnpinchangeActionPerformed

    private void btnbalanceenquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbalanceenquiryActionPerformed
        BalanceEnquiry balanceEnquiry = new BalanceEnquiry(this.signinName, this.signinEmail, this.signinCardno, this.signinPin, this.balance);
        balanceEnquiry.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnbalanceenquiryActionPerformed

    private void btnministatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnministatementActionPerformed
        // TODO add your handling code here:
        MiniStatement miniStatement = new MiniStatement(this.signinName, this.signinEmail, this.signinCardno, this.signinPin, this.balance);

        miniStatement.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnministatementActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnwithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnwithdrawalActionPerformed
        Withdrawal withdraw = new Withdrawal(this.signinName, this.signinEmail, this.signinCardno, this.signinPin, this.balance);
        withdraw.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnwithdrawalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbalanceenquiry;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndeposit;
    private javax.swing.JButton btnfastcash;
    private javax.swing.JButton btnministatement;
    private javax.swing.JButton btnpinchange;
    private javax.swing.JButton btnwithdrawal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_bankname1;
    private javax.swing.JLabel lbl_banktext1;
    // End of variables declaration//GEN-END:variables
}
